[project]
name = "agop-eigen-alignment-jax"
version = "0.1.0"
requires-python = ">=3.12"

dependencies = [
    "numpy",
    "scipy",
    "matplotlib",
    "pandas",
    "jax",
    "jaxlib",
    "optax",
    "flax",
    "tqdm",
    "requests",
    "pyyaml",
    "pillow",
    "wandb",
    "jupyterlab",
    "ipykernel",
    "ipympl",
    "ipywidgets",
]